[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
  command = "npm run build"
  publish = "_site"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "npm run start"
  targetPort = 8080

# Production context
[context.production.environment]
  GITHUB_REPO_OWNER = "quietloudlab"
  GITHUB_REPO_NAME = "brandonharwood-site"

# Deploy Preview context
[context.deploy-preview.environment]
  GITHUB_REPO_OWNER = "quietloudlab"
  GITHUB_REPO_NAME = "brandonharwood-site"

# Branch Deploy context
[context.branch-deploy.environment]
  GITHUB_REPO_OWNER = "quietloudlab"
  GITHUB_REPO_NAME = "brandonharwood-site"

# Development environment
[context.dev.environment]
  GITHUB_REPO_OWNER = "quietloudlab"
  GITHUB_REPO_NAME = "brandonharwood-site"
