backend:
  name: git-gateway
  branch: main  # Adjust based on your branch name

media_folder: "src/static/images"  # Where uploaded images are stored
public_folder: "/static/images"  # Path Netlify CMS uses to access images

collections:
  - name: "weblogs"
    label: "weblog"
    folder: "src/content/weblogs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }  # Automatically assign layout
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Tags", name: "tags", widget: "list", allow_add: true }
      - { label: "Enable Comments", name: "comments", widget: "boolean", default: true }
      - { label: "Enable Sharing", name: "sharing", widget: "boolean", default: true }

  - name: "collections"
    label: "collection"
    folder: "src/content/collections"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "collection" }
      - { 
          label: "Items", 
          name: "items", 
          widget: "list",
          fields: [
            { label: "Type", name: "type", widget: "select", options: ["link", "image", "snippet"] },
            { label: "Content", name: "content", widget: "string", hint: "URL, image path, or text snippet" },
            { label: "Note", name: "note", widget: "text", required: false }
          ]
        }

  - name: "made-things"
    label: "made thing"
    folder: "src/content/made-things"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "experiment" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Link to Project", name: "link", widget: "string", hint: "URL to the external or internal project" }
      - { label: "Status", name: "status", widget: "select", options: ["in progress", "completed"], default: "in progress" }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }

  - name: "weird-interactions"
    label: "weird interaction"
    folder: "src/content/weird-interactions"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "interaction" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Embed Code", name: "embed_code", widget: "code", default_language: "html" }
      - { label: "Widget Mode", name: "widget_mode", widget: "boolean", default: false }
      - { label: "Code Language", name: "code_language", widget: "select", options: ["HTML", "CSS", "JavaScript", "Processing", "WebGL"] }

  - name: "questions"
    label: "answered question"
    folder: "src/content/questions"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Question", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Category", name: "category", widget: "select", options: ["personal", "technical", "creative process", "philosophy"] }
      - { label: "Answer", name: "body", widget: "markdown" }
      - { label: "Related Links", name: "links", widget: "list", field: { label: "Link", name: "link", widget: "string" } }
