backend:
  name: git-gateway
  branch: main  # Adjust based on your branch name

media_folder: "src/static/images"  # Where uploaded images are stored
public_folder: "/static/images"  # Path Netlify CMS uses to access images

collections:
  - name: "weblogs"
    label: "weblog"
    folder: "src/content/weblogs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Featured Image", name: "image", widget: "image" }

  - name: "collections"
    label: "collection"
    folder: "src/content/collections"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "made-things"
    label: "made thing"
    folder: "src/content/made-things"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Link", name: "link", widget: "string" }

  - name: "weird-interactions"
    label: "weird interaction"
    folder: "src/content/weird-interactions"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Code Embed", name: "embed_code", widget: "code", default_language: "html" }

  - name: "questions"
    label: "answered question"
    folder: "src/content/answered-questions"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Question", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Answer", name: "body", widget: "markdown" }
      - { label: "Related Links", name: "links", widget: "list", field: { label: "Link", name: "link", widget: "string" } }
